name: Greeting Pipeline

on:
#   push:
#     branches:
#       - main
    workflow_dispatch:
        inputs:
          build_id:
            required: true
            type: number
jobs:
  greet:
    runs-on: ubuntu-latest
#     parameters:
#       name:
#         type: string
#         description: "The name of the person to greet"
#         required: true
    steps:
      - run: |
          echo "Hello, ${{ inputs.build_id }}!"
