name: Deploy Pod to Minikube

on:
#   push:
#     branches:
#       - main
  workflow_dispatch:
      

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3


    - name: Start Minikube
      run: |
        curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 \
        && chmod +x minikube && sudo mv minikube /usr/local/bin/

    - name: Start Minikube Cluster
      run: |
        sudo minikube start --vm-driver=none --kubernetes-version=$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)

    - name: Configure Kubernetes CLI
      uses: azure/k8s-set-context@v1
      with:
        kubeconfig: ~/.kube/config
        method: kubeconfig
        context: minikube

    - name: Deploy Pod
      run: kubectl apply -f pod.yaml

    - name: number of pods
      run: kubectl get pods
