name: Deploy Pod to Minikube

on:
#   push:
#     branches:
#       - main
  workflow_dispatch:
      

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3


    - name: Start Minikube
      run: |
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo install minikube-linux-amd64 /usr/local/bin/minikube


    - name: Start Minikube Cluster
      run: |
        sudo minikube start 

    - name: Configure Kubernetes CLI
      uses: azure/k8s-set-context@v1
      with:
        kubeconfig: ~/.kube/config
        method: kubeconfig
        context: minikube

    - name: Deploy Pod
      run: kubectl apply -f pod.yaml

    - name: number of pods
      run: kubectl get pods
